# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  style_check:
    working_directory: /tmp/src/cis-processing
    docker:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Generate environment
          command: |
            conda create -n venv python=2.7 pylint -yq
            source activate venv
            pip install 'flake8<3.0' flake8-putty
      - run:
          name: Style check
          command: |
            source activate venv
            flake8 --max-line-length=100 --exclude=heuristics /tmp/src/cis-processing
workflows:
  version: 2.1
  build_test:
    jobs:
      - style_check
